Busan-Dinosaur/FoodBowl-iOS

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/UIComponent/MainButton.swift
- FoodBowl/Screens/Main/Cell/FeedCollectionViewCell.swift
- FoodBowl/Screens/Main/Cell/RegionCollectionViewCell.swift
- FoodBowl/Screens/Main/Cell/StateCollectionViewCell.swift
- FoodBowl/Screens/Main/MainViewController.swift
- FoodBowl/Screens/Main/RegionViewController.swift
- FoodBowl/Screens/Main/UIComponent/EmptyFeedView.swift
- FoodBowl/Screens/Main/UIComponent/RegionTagListView.swift
- FoodBowl/Screens/Main/UIComponent/StateTagListView.swift
메인화면에서 지역 태그 필터링과, 피드 목록을 볼 수 있도록 구현하였습니다.
- FeedCell을 CollectionView로 구현
- 지역 태그 설정 팝업 추가
- UserDefaults로 선택한 지역 태그 저장
- 하단으로 당길 시에, UIRefreshControl을 통해 새로고침
<p align="left">
</p>
- close #5
> [FEAT] Main 뷰 디자인 구현

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Screens/Search/Cell/FeedThumnailCollectionViewCell.swift
- FoodBowl/Screens/Search/SearchViewController.swift
검색 화면에서 후기를 검색하는 UI를 구현하였습니다.
- SearchBar 구현
- 피드 섬네일 구현
- close #7
> [ADD] 검색화면 디자인 구현

- FoodBowl/Screens/Message/Cell/ChannelTableViewCell.swift
- FoodBowl/Screens/Message/MessageViewController.swift
메시지 화면에서 채팅방 목록을 볼 수 있도록 구현하였습니다.
- Channel 셀을 컬렉션뷰로 구현
- close #8
> [ADD] Message 뷰 디자인 구현

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/UIComponent/UserInfoView.swift
- FoodBowl/Screens/Main/Cell/FeedCollectionViewCell.swift
- FoodBowl/Screens/Main/MainViewController.swift
메인뷰에서 아쉬운 부분을 수정합니다.
- 유저 정보 컴포넌트화
- 지역 태그 위치 조정
- close #12
> [CHORE] 메인뷰 수정

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Base/BaseScrollView.swift
- FoodBowl/Global/Base/HorizontalScrollView.swift
- FoodBowl/Global/Literal/ImageLiteral.swift
- FoodBowl/Global/Resource/Assets.xcassets/food1.imageset/Contents.json
- FoodBowl/Global/Resource/Assets.xcassets/food2.imageset/Contents.json
- FoodBowl/Global/Resource/Assets.xcassets/food3.imageset/Contents.json
- FoodBowl/Global/UIComponent/ScrapButton.swift
- FoodBowl/Global/UIComponent/StoreInfoView.swift
- FoodBowl/Screens/Feed/FeedDetailViewController.swift
- FoodBowl/Screens/Feed/UIComponent/CommentView.swift
- FoodBowl/Screens/Main/Cell/FeedCollectionViewCell.swift
- FoodBowl/Screens/Main/MainViewController.swift
- FoodBowl/Screens/Profile/UIComponent/UserProfileView.swift
피드 디테일 화면입니다.
이번 MVP 단계에서 삭제될 예정이지만, 유용한 코드가 많아 PR을 올립니다.
- 사진 가로 스크롤 기능
- 풀 모달 띄우기
- 후기 정보뷰
- close #15
> [FEAT] FeedDetail 뷰 디자인 구현

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Literal/ImageLiteral.swift
- FoodBowl/Global/UIComponent/CloseButton.swift
- FoodBowl/Screens/Feed/AddFeedViewController.swift
- FoodBowl/Screens/Feed/SetPhotoViewController.swift
- FoodBowl/Screens/Main/MainViewController.swift
피드를 등록하는 플로우를 Page뷰컨으로 구현하였습니다.
- PageViewController에 등록과정 뷰컨들 추가
- 뷰컨에 따라 네비게이션이 변하는, `updateNavigationBar`함수 생성
https://user-images.githubusercontent.com/57849386/212153043-6a674424-2f2a-41dd-a43c-42fdf18aa79c.mp4
- close #22
> [FEAT] PageViewController 구현

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Extensions/UILabel+Extension.swift
- FoodBowl/Global/Extensions/UIView+Extension.swift
- FoodBowl/Global/UIComponent/SearchBarButton.swift
- FoodBowl/Models/Place.swift
- FoodBowl/Screens/Feed/AddFeedViewController.swift
- FoodBowl/Screens/Feed/Cell/StoreInfoTableViewCell.swift
- FoodBowl/Screens/Feed/SearchStoreViewController.swift
- FoodBowl/Screens/Feed/SetStoreViewController.swift
- FoodBowl/Screens/Feed/UIComponent/SelectedStoreView.swift
피드를 등록하고자 하는 가게를 선택하는 뷰를 구현하였습니다.
- 가게검색 팝업은 pageSheet로 구현
- SearchBar를 UITextField로, 가게 목록은 UITableView로 구현하였습니다.
- 검색된 가게들 중에 선택한 가게를 Delegate를 통해 데이터를 부모뷰로 보냈습니다.
https://user-images.githubusercontent.com/57849386/212344350-74682c1e-1be7-4db5-ae9f-a71354e9679f.mp4
- close #16
> [FEAT] 가게선택 뷰

- FoodBowl/Screens/Map/MapViewController.swift
지도탭 화면에서 지도를 띄웠습니다.
- MKMapView를 사용하여 기본 애플 지도를 띄웟습니다.
- MKUserTrackingButton로 현재 위치를 찾는 버튼을 만들었습니다.
- close #27
> [FEAT] 지도탭 화면 구현

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Models/Place.swift
- FoodBowl/Screens/Feed/Cell/CategoryCollectionViewCell.swift
- FoodBowl/Screens/Feed/SetCategoryViewController.swift
- FoodBowl/Screens/Feed/SetStoreViewController.swift
후기를 남길 가게의 카테고리를 선택하는 화면을 구현하였습니다.
- 가게 카테고리 Enum으로 구현
- 카테고리 라벨에 따라 유동적인 컬렉션뷰셀 생성
- isSelected로 선택된 셀의 스타일 변경
https://user-images.githubusercontent.com/57849386/212549223-ca19ded4-5ffb-4d24-bdfb-b59fc6b26a5c.mp4
- close #29
> [FEAT] SetCategory 뷰 디자인 구현

- FoodBowl/Screens/Feed/SetCommentViewController.swift
후기를 입력하는 뷰를 만들었습니다.
- 여러줄을 입력할 수 있는 UITextField로 입력창을 만들었습니다.
- ios15부터 적용되는 `keyboardLayoutGuide`로 텍스트뷰 위치를 조정하였습니다.
- close #18
> [FEAT] SetComment 구현

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Models/Feed.swift
- FoodBowl/Models/Place.swift
- FoodBowl/Screens/Feed/AddFeedViewController.swift
- FoodBowl/Screens/Feed/SetCategoryViewController.swift
- FoodBowl/Screens/Feed/SetCommentViewController.swift
- FoodBowl/Screens/Feed/SetPhotoViewController.swift
- FoodBowl/Screens/Feed/SetStoreViewController.swift
피드 등록과정에서의 UX 향상을 위해 디테일을 수정하였습니다.
- 빈 데이터일 때, 넘어가지 못함
- 후기 작성할 때, 선택한 사진보기 -> `Delegate` 활용
- close #33
> [FEAT] 피드 등록과정 디테일 수정

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/UIComponent/Marker.swift
- FoodBowl/Screens/Main/Cell/FeedCommentTableViewCell.swift
- FoodBowl/Screens/Main/FeedCommentViewController.swift
- FoodBowl/Screens/Main/MainViewController.swift
- FoodBowl/Screens/Main/StoreFeedViewController.swift
- FoodBowl/Screens/Map/FindStoreViewController.swift
- FoodBowl/Screens/Map/MapViewController.swift
맵뷰에서 마커를 클릭하고, 해당 가게의 피드를 볼 수 있는 플로우를 구현하였습니다.
- 가게 댓글뷰 구현
- 가게 검색뷰 구현
- 가게 피드뷰 구현
- 지도 마커 구현 및 뷰 연결
- close #43
https://www.kodeco.com/7738344-mapkit-tutorial-getting-started
> [FEAT] Map 뷰 마커 및 플로우 연결

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Extensions/UIButton+Extension.swift
- FoodBowl/Global/UIComponent/CheckBox.swift
- FoodBowl/Screens/Sign/AgreementViewController.swift
- FoodBowl/Screens/Sign/OnboardingViewController.swift
회원가입시에 약관 동의 화면을 구현하였습니다.
- 약관 동의 체크박스 구현
- 약관 동의 웹뷰 구현
https://user-images.githubusercontent.com/57849386/214912103-3364b2b9-c83c-4bfe-8ebb-fa686e1ef418.mp4
- close #55
> [FEAT] 약관 동의 화면 구현

- FoodBowl.xcodeproj/xcuserdata/coby.xcuserdatad/xcschemes/xcschememanagement.plist
- FoodBowl/Global/UIComponent/MapItem.swift
- FoodBowl/Screens/Feed/AddFeedViewController.swift
- FoodBowl/Screens/Feed/SetStoreViewController.swift
- FoodBowl/Screens/Feed/ShowWebViewController.swift
- FoodBowl/Screens/Main/Cell/ChatTableViewCell.swift
- FoodBowl/Screens/Main/ChatViewController.swift
- FoodBowl/Screens/Main/MainViewController.swift
- FoodBowl/Screens/Main/StoreFeedViewController.swift
- FoodBowl/Screens/Map/FindStoreViewController.swift
- FoodBowl/Screens/Map/MapViewController.swift
- FoodBowl/Screens/Profile/ProfileViewController.swift
- FoodBowl/Screens/Profile/SettingViewController.swift
- FoodBowl/Screens/Profile/UserFeedViewController.swift
- FoodBowl/Screens/Search/SearchViewController.swift
- FoodBowl/Screens/Sign/AgreementViewController.swift
- FoodBowl/Screens/Sign/SetProfileViewController.swift
앱의 전반적인 불친절한 요소를 줄였습니다.
- 동의약관 및 공지를 노션링크로 연결
- 회원가입시 닉네임 글자수 제한
- 섬네일 네비게이션 연결
- 맵뷰 마커 게시물보기 클릭시 팝업에서 푸시로 변경
- 신고하기 Alert 추가
- 게시물 등록시에 Alert 안내 추가
- close #59
> [FEAT] 앱 디테일 수정

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Cell/CategoryCollectionViewCell.swift
- FoodBowl/Global/UIComponent/ForwordButton.swift
- FoodBowl/Screens/Main/Cell/ChatTableViewCell.swift
- FoodBowl/Screens/Main/Cell/FeedCollectionViewCell.swift
- FoodBowl/Screens/Main/ChatViewController.swift
- FoodBowl/Screens/Main/MainViewController.swift
- FoodBowl/Screens/Main/UIComponent/ChatSendView.swift
- FoodBowl/Screens/Map/MapViewController.swift
- FoodBowl/Screens/Profile/EditProfileViewController.swift
- FoodBowl/Screens/Profile/SettingViewController.swift
- FoodBowl/Screens/Sign/AgreementViewController.swift
메인뷰에서 피드내의 버튼을 눌렀을 때, 네비게이션이 중첩되어 뜨는 오류를 확인하였습니다.
우선 메인뷰에서만, 그 오류를 해결하였습니다.
컬렉션뷰 셀이 재사용되면서 `addAction`이 중첩되었습니다. 부모뷰에서 `handler`를 만들어주고 셀에서 받는 구조로 변경하였습니다.
https://user-images.githubusercontent.com/57849386/215819589-b029821d-ddea-4c80-b168-d0226809ebda.mp4
- close #63
> [FEAT] 메인뷰 컬렉션뷰 오류 수정

- FoodBowl/Screens/Feed/SetCommentViewController.swift
후기 작성뷰에서 텍스트뷰 폰트 색 수정하여, 다크모드를 적용시켰습니다.
- close #70
> [FEAT] 텍스트뷰 폰트 색 수정

- FoodBowl/Screens/Feed/ShowWebViewController.swift
웹뷰에서 다른앱 열기 허용하도록 설정을 수정하였습니다.
- close #69
> [FEAT] 웹뷰에서 다른앱 열기 허용

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Base/BaseViewController.swift
- FoodBowl/Global/Extensions/Notification+Extension.swift
- FoodBowl/Global/Extensions/String+Extension.swift
- FoodBowl/Global/Supports/AppDelegate.swift
- FoodBowl/Global/Supports/SceneDelegate.swift
- FoodBowl/Global/Supports/TabBarController.swift
- FoodBowl/Global/UIComponent/FollowButton.swift
- FoodBowl/Global/UIComponent/ForwardButton.swift
- FoodBowl/Global/Utils/LocationManager.swift
- FoodBowl/Screens/Feed/SearchStoreViewController.swift
- FoodBowl/Screens/Main/MainViewController.swift
- FoodBowl/Screens/Map/MapViewController.swift
- FoodBowl/Screens/Profile/Cell/SettingItemTableViewCell.swift
- FoodBowl/Screens/Profile/EditProfileViewController.swift
- FoodBowl/Screens/Sign/OnboardingViewController.swift
- FoodBowl/Screens/Sign/SetProfileViewController.swift
지도 관련 코드를 LocationManager로 싱글톤화 하였습니다.
- close #77
> [FEAT] 지도 코드 수정

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Screens/Main/Cell/FeedCollectionViewCell.swift
- FoodBowl/Screens/Main/MainViewController.swift
> [FEAT] 오류 수정 및 버전 업

- FoodBowl/Screens/Feed/AddFeedViewController.swift
- FoodBowl/Screens/Feed/SearchStoreViewController.swift
- FoodBowl/Screens/Feed/SetStoreViewController.swift
리뷰를 추가하는 과정에서, 카테고리와 대학가를 설정하는 과정을 자동화합니다.
- close #86
> [FEAT] 가게 선택시 카테고리와 대학가 추가

- FoodBowl.xcodeproj/project.pbxproj
- FoodBowl/Global/Supports/TabBarController.swift
- FoodBowl/Screens/Bookmark/View/BookmarkViewController.swift
- FoodBowl/Screens/Bookmark/View/Cell/BookmarkCollectionViewCell.swift
- FoodBowl/Screens/Bookmark/View/Component/BookmarkListView.swift
- FoodBowl/Screens/Friend/View/Component/FriendFeedView.swift
- FoodBowl/Screens/Friend/View/FriendViewController.swift
- FoodBowl/Screens/Map/View/Cell/CategoryCollectionViewCell.swift
- FoodBowl/Screens/Map/View/Component/GrabbarView.swift
- FoodBowl/Screens/Map/View/Component/ModalView.swift
- FoodBowl/Screens/Map/View/MapViewController.swift
- FoodBowl/Screens/Profile/View/ProfileViewController.swift
- FoodBowl/Screens/Univ/View/UnivViewController.swift
북마크 목록 모달을 구현하고,
모달 UX향상을 위해 그랩바의 높이를 늘리고, 모달의 헤더를 수정하였습니다.
- 북마크 목록 컬렉션뷰 구현
- 모달의 그랩바 높이 확장 -> 모달끌기 UX 향상
- close #101
> [FEAT] 북마크 목록뷰 구현 및 모달 헤더 수정
